const { contextBridge, ipcRenderer } = require('electron');

const invoke = (...args) => ipcRenderer.invoke(...args);

contextBridge.exposeInMainWorld('mangaAPI', {
  bootstrap: () => invoke('app:bootstrap'),
  getCompactIndex: () => invoke('app:getCompactIndex'),
  signalBootReady: () => ipcRenderer.send('app:boot-ready'),
  markInteraction: () => ipcRenderer.send('app:mark-interaction'),
  setReaderActive: (active) => ipcRenderer.send('reader:set-active', active),

  addCategories: () => invoke('library:addCategories'),
  removeCategory: (categoryId) => invoke('library:removeCategory', categoryId),
  trashManga: (mangaId) => invoke('library:trashManga', mangaId),
  toggleCategoryHidden: (categoryId) => invoke('library:toggleCategoryHidden', categoryId),
  getChapterPages: (chapterPath) => invoke('library:getChapterPages', chapterPath),
  readPdfData: (filePath) => invoke('library:readPdfData', filePath),
  pickCover: (mangaId) => invoke('library:pickCover', mangaId),
  updateMetadata: (mangaId, patch) => invoke('library:updateMetadata', mangaId, patch),
  toggleFavorite: (mangaId) => invoke('library:toggleFavorite', mangaId),
  bulkFavorite: (mangaIds, nextValue) => invoke('library:bulkFavorite', mangaIds, nextValue),
  setPrivateFlag: (mangaId, isPrivate) => invoke('library:setPrivateFlag', mangaId, isPrivate),
  setPrivateFlagMany: (mangaIds, isPrivate) => invoke('library:setPrivateFlagMany', mangaIds, isPrivate),
  setPrivateCategoryFlag: (categoryId, isPrivate) => invoke('library:setPrivateCategoryFlag', categoryId, isPrivate),
  forceRescan: () => invoke('library:forceRescan'),
  getSyncStatus: () => invoke('library:getSyncStatus'),
  runDeepScan: () => invoke('library:runDeepScan'),
  searchAdvanced: (input) => invoke('search:advanced', input),
  listSeries: (input) => invoke('series:list', input),
  getSeriesDetail: (seriesRef) => invoke('series:getDetail', seriesRef),
  getSeriesChapters: (seriesRef, options) => invoke('series:getChapters', seriesRef, options),
  getChapterDetail: (chapterRef) => invoke('chapter:getDetail', chapterRef),
  getReaderPagesV2: (chapterRef) => invoke('reader:getPages', chapterRef),
  saveReaderProgressV2: (payload) => invoke('reader:saveProgress', payload),
  searchLibrary: (input) => invoke('search:query', input),
  runSmartFilter: (filter) => invoke('filters:run', filter),
  getMigrationStatus: () => invoke('migration:getStatus'),
  analyzeMigration: () => invoke('migration:analyze'),
  runMigration: (options) => invoke('migration:run', options),
  restoreMigrationBackup: (input) => invoke('migration:restoreBackup', input),
  listMigrationBackups: () => invoke('migration:listBackups'),
  cleanupLegacyStorage: (input) => invoke('migration:cleanupLegacyStorage', input),

  updateProgress: (payload) => invoke('reading:updateProgress', payload),
  updateProgressLight: (payload) => invoke('reading:updateProgressLight', payload),
  setReadStatus: (mangaId, isRead, chapterIds) => invoke('reading:setReadStatus', mangaId, isRead, chapterIds),
  setChapterReadStatus: (mangaId, chapterId, isRead, pageCount) => invoke('reading:setChapterReadStatus', mangaId, chapterId, isRead, pageCount),
  resetProgress: (mangaId, chapterIds) => invoke('reading:resetProgress', mangaId, chapterIds),
  resetChapterProgress: (chapterId) => invoke('reading:resetChapterProgress', chapterId),
  bulkSetReadStatus: (entries, isRead) => invoke('reading:bulkSetReadStatus', entries, isRead),

  createTag: (name, color) => invoke('tags:create', name, color),
  deleteTag: (tagId) => invoke('tags:delete', tagId),
  addTagToManga: (mangaId, tagId) => invoke('tags:addToManga', mangaId, tagId),
  removeTagFromManga: (mangaId, tagId) => invoke('tags:removeFromManga', mangaId, tagId),
  setMangaTags: (mangaId, tagIds) => invoke('tags:setForManga', mangaId, tagIds),
  toggleMangaTag: (mangaId, tagId) => invoke('tags:toggleForManga', mangaId, tagId),
  addTagToMany: (tagId, mangaIds) => invoke('tags:addMany', tagId, mangaIds),

  createCollection: (name, description, color) => invoke('collections:create', name, description, color),
  deleteCollection: (collectionId) => invoke('collections:delete', collectionId),
  updateCollection: (collectionId, patch) => invoke('collections:update', collectionId, patch),
  addMangaToCollection: (collectionId, mangaId) => invoke('collections:addManga', collectionId, mangaId),
  removeMangaFromCollection: (collectionId, mangaId) => invoke('collections:removeManga', collectionId, mangaId),
  addManyToCollection: (collectionId, mangaIds) => invoke('collections:addMany', collectionId, mangaIds),
  saveSmartCollection: (collection) => invoke('smartCollections:save', collection),
  deleteSmartCollection: (collectionId) => invoke('smartCollections:delete', collectionId),

  searchOnlineMetadata: (query) => invoke('metadata:searchOnline', query),
  importOnlineMetadata: (mangaId, onlineData) => invoke('metadata:importOnline', mangaId, onlineData),
  queueMetadataWorkbench: (mangaIds, mode) => invoke('metadata:queueWorkbench', mangaIds, mode),
  setMetadataWorkbenchQueue: (mangaIds) => invoke('metadata:setWorkbenchQueue', mangaIds),
  updateMetadataFieldLocks: (mangaId, patch) => invoke('metadata:updateFieldLocks', mangaId, patch),
  importComicInfo: (mangaId, options) => invoke('metadata:importComicInfo', mangaId, options),

  upsertReadingQueueItem: (item) => invoke('queue:upsert', item),
  removeReadingQueueItem: (item) => invoke('queue:remove', item),
  saveReadingQueue: (items) => invoke('queue:save', items),

  addAnnotation: (input) => invoke('annotations:add', input),
  deleteAnnotation: (mangaId, annotationId) => invoke('annotations:delete', mangaId, annotationId),

  createBackup: (label) => invoke('backup:create', label),
  importBackup: () => invoke('backup:import'),
  listBackups: () => invoke('backup:list'),
  exportBackup: () => invoke('backup:export'),

  updateSettings: (patch) => invoke('ui:updateSettings', patch),
  updateSettingsLight: (patch) => invoke('ui:updateSettingsLight', patch),
  pickBackgroundImage: () => invoke('ui:pickBackgroundImage'),
  removeBackgroundImage: () => invoke('ui:removeBackgroundImage'),
  getVisualPrefs: (mangaRef) => invoke('reader:getVisualPrefs', mangaRef),
  setVisualPrefs: (mangaRef, patch) => invoke('reader:setVisualPrefs', mangaRef, patch),
  getPanelMap: (chapterRef) => invoke('guidedView:getPanelMap', chapterRef),
  savePanelMap: (chapterRef, panelMap) => invoke('guidedView:savePanelMap', chapterRef, panelMap),
  saveTabsSession: (payload) => invoke('session:saveTabs', payload),
  setVaultPin: (pin) => invoke('vault:setPin', pin),
  unlockVault: (pin) => invoke('vault:unlock', pin),
  lockVault: () => invoke('vault:lock'),
  updateVaultPrefs: (patch) => invoke('vault:updatePrefs', patch),
  updateVaultPrefsLight: (patch) => invoke('vault:updatePrefsLight', patch),

  minimizeWindow: () => invoke('window:minimize'),
  toggleMaximizeWindow: () => invoke('window:toggleMaximize'),
  closeWindow: () => invoke('window:close'),
  toggleFullScreen: () => invoke('window:toggleFullScreen'),

  clearCache: () => invoke('maintenance:clearCache'),
  rebuildIndex: () => invoke('maintenance:rebuildIndex'),
  getStats: (options) => invoke('maintenance:getStats', options),
  getDuplicateCandidates: () => invoke('maintenance:getDuplicateCandidates'),
  rebuildDerivedData: () => invoke('maintenance:rebuildDerivedData'),
  listJobs: () => invoke('jobs:list'),
  cancelJob: (jobId) => invoke('jobs:cancel', jobId),
  retryJob: (jobId) => invoke('jobs:retry', jobId),
  listOcrLanguages: () => invoke('ocr:listLanguages'),
  enqueueOcr: (payload) => invoke('ocr:enqueue', payload),
  pauseOcr: () => invoke('ocr:pause'),
  resumeOcr: () => invoke('ocr:resume'),
  cancelOcr: (jobId) => invoke('ocr:cancel', jobId),
  purgeOcr: () => invoke('ocr:purge'),
  exportComicInfo: (payload) => invoke('comicinfo:export', payload),

  listPlugins: () => invoke('plugins:list'),
  setPluginEnabled: (pluginId, enabled) => invoke('plugins:setEnabled', pluginId, enabled),
  installPlugin: (pluginId) => invoke('plugins:install', pluginId),
  uninstallPlugin: (pluginId) => invoke('plugins:uninstall', pluginId),
  openPlugin: (pluginId) => invoke('plugins:open', pluginId),

  listSourceConnectors: () => invoke('sources:listConnectors'),
  getSourceRuntimeStatus: () => invoke('sources:getRuntimeStatus'),
  startSourceRuntime: () => invoke('sources:startRuntime'),
  stopSourceRuntime: () => invoke('sources:stopRuntime'),
  resetSourceRuntimeCache: () => invoke('sources:resetRuntimeCache'),
  listSourceRepositories: () => invoke('sources:listRepositories'),
  addSourceRepository: (input) => invoke('sources:addRepository', input),
  removeSourceRepository: (repositoryId) => invoke('sources:removeRepository', repositoryId),
  syncSourceRepositories: () => invoke('sources:syncRepositories'),
  listSourceExtensions: () => invoke('sources:listExtensions'),
  installSourceExtension: (extensionId) => invoke('sources:installExtension', extensionId),
  updateSourceExtension: (extensionId) => invoke('sources:updateExtension', extensionId),
  uninstallSourceExtension: (extensionId) => invoke('sources:uninstallExtension', extensionId),
  setSourceExtensionEnabled: (extensionId, enabled) => invoke('sources:setExtensionEnabled', extensionId, enabled),
  getSourceConnectorPrefs: (connectorId) => invoke('sources:getConnectorPrefs', connectorId),
  setSourceConnectorPrefs: (input) => invoke('sources:setConnectorPrefs', input),
  searchSourceSeries: (input) => invoke('sources:searchSeries', input),
  getSourceSeries: (input) => invoke('sources:getSeries', input),
  getSourceChapters: (input) => invoke('sources:getChapters', input),
  listLinkedSourceSeries: () => invoke('sources:listLinkedSeries'),
  getSourceSeriesContextForManga: (input) => invoke('sources:getSeriesContextForManga', input),
  getSourceSeriesChaptersForManga: (input) => invoke('sources:getSeriesChaptersForManga', input),
  checkSourceUpdatesForManga: (input) => invoke('sources:checkUpdatesForManga', input),
  openSourceSeriesContext: (input) => invoke('sources:openSeriesContext', input),
  enqueueSourceImport: (input) => invoke('sources:enqueueImport', input),
  listSourceImports: () => invoke('sources:listImports'),
  cancelSourceImport: (jobId) => invoke('sources:cancelImport', jobId),

  onLibraryChanged: (callback) => {
    const handler = (_event, ...args) => callback(...args);
    ipcRenderer.on('library:changed', handler);
    return () => ipcRenderer.removeListener('library:changed', handler);
  },
  onSyncStatusChanged: (callback) => {
    const handler = (_event, ...args) => callback(...args);
    ipcRenderer.on('library:syncStatusChanged', handler);
    return () => ipcRenderer.removeListener('library:syncStatusChanged', handler);
  }
});
